[tox]
envlist = py39,py310,py311,py312,py313
isolated_build = true

# Unit test env
[testenv]
extras = dev
commands = pytest tests/unit {posargs}

# Integration test
[testenv:{py39,py310,py311,py312,py313}-all]
extras = dev
setenv =
    RADICAL_VERBOSE=DEBUG
commands_pre = 
    radical-stack
commands = pytest tests/integration {posargs}

# Linting
[testenv:lint]
extras = lint
commands = 
    ruff check ddmd tests
    ruff format --check ddmd tests

# Formatting
[testenv:format]
extras = lint
commands = 
    ruff format ddmd tests
    ruff check --fix ddmd tests

# Coverage
[testenv:coverage]
extras = dev
commands = pytest --cov=ddmd --cov-report=html --cov-report=term {posargs}
