#!/bin/bash
# Summitdev OpenMM testing
#BSUB -P LRN005 
#BSUB -J test_omm_ppc
#BSUB -o tst.o%J
#BSUB -W 1:00
#BSUB -nnodes 1
# End LSF directives and begin shell commands
date
source activate omm 
module load cuda/9.1.85 
export PYTHONPATH=$PYTHONPATH:/gpfs/alpine/scratch/hm0/bip179/entk_MDs/experiments_folding/NTL9/MD_exps
jsrun -n 1 -a 1 -g 1 python run_openmm.py -f pdb/ntl9.pdb -p pdb/ntl9.top 
# python run_openmm.py -f pdb/100-fs-peptide-400K.pdb 
